# Generated by Django 5.1.4 on 2024-12-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_alter_city_options_alter_country_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="common_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Common Name"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="currency",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="exports",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="fauna",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="flora",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="geography",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Official Name"),
        ),
    ]
