# Generated by Django 5.1.4 on 2024-12-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "places",
            "0003_country_common_name_country_currency_country_exports_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FlagColour",
            fields=[
                (
                    "colour",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "verbose_name_plural": "Flag Colours",
            },
        ),
        migrations.AddField(
            model_name="country",
            name="flag_colours",
            field=models.ManyToManyField(blank=True, to="places.flagcolour"),
        ),
    ]
