# Generated by Django 5.1.4 on 2024-12-14 21:55

from django.db import migrations
from django.db.models import F


def populate_common_name(apps, schema_editor):
    Country = apps.get_model("places", "Country")
    Country.objects.filter(common_name__isnull=True).update(common_name=F("name"))


def undo_common_name(apps, schema_editor):
    Country = apps.get_model("places", "Country")
    Country.objects.filter(common_name=F("name")).update(common_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_flagcolour_country_flag_colours"),
    ]

    operations = [
        migrations.RunPython(populate_common_name, undo_common_name),
    ]
