# Generated by Django 5.1.4 on 2024-12-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_data__common_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('common_name',), 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='country',
            name='common_name',
            field=models.CharField(max_length=50, verbose_name='Common Name'),
        ),
    ]
