# Generated by Django 5.1.4 on 2025-06-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_alter_country_options_alter_country_common_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="government",
            field=models.TextField(
                blank=True, help_text="Type of government", null=True
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="history",
            field=models.TextField(
                blank=True, help_text="Historical events and periods", null=True
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="exports",
            field=models.TextField(
                blank=True, help_text="Produce and goods", null=True
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="fauna",
            field=models.TextField(blank=True, help_text="Animals", null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="flora",
            field=models.TextField(blank=True, help_text="Plants", null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="geography",
            field=models.TextField(
                blank=True, help_text="Landmarks or landforms", null=True
            ),
        ),
    ]
