# Generated by Django 5.1.4 on 2024-12-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Suspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sex",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "hobby",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TENNIS", "Tennis"),
                            ("MUSIC", "Music"),
                            ("CLIMBING", "Mountain Climbing"),
                            ("SKYDIVE", "Skydiving"),
                            ("SWIMMING", "Swimming"),
                            ("CROQUET", "Croquet"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "hair",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BROWN", "Brown"),
                            ("BLONDE", "Blonde"),
                            ("RED", "Red"),
                            ("BLACK", "Black"),
                            ("GREY", "Grey"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LIMP", "Limps"),
                            ("RING", "Ring"),
                            ("TATTOO", "Tattoo"),
                            ("SCAR", "Scar"),
                            ("JEWELERY", "Jewelery"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "auto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONVERTIBLE", "Convertible"),
                            ("LIMO", "Limousine"),
                            ("RACECAR", "Racecar"),
                            ("MOTORBIKE", "Motorcycle"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
