# Generated by Django 5.1.4 on 2024-12-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("criminals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suspect",
            name="has_picture",
            field=models.BooleanField(default=False),
        ),
    ]
