# Generated by Django 5.1.4 on 2024-12-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0002_suspect_has_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='food',
            field=models.CharField(blank=True, choices=[('SEAFOOD', 'Seafood'), ('MEXICAN', 'Mexican')], db_index=True, max_length=20, null=True),
        ),
    ]
