# Generated by Django 5.2.6 on 2025-09-13 06:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criminals', '0003_suspect_food'),
        ('places', '0007_country_government_country_history_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('stolen_artifact', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('ROOKIE', 'Rookie'), ('DETECTIVE', 'Detective'), ('INSPECTOR', 'Inspector'), ('CHIEF', 'Chief Inspector')], default='ROOKIE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminals.suspect')),
                ('target_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.country')),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_type', models.CharField(choices=[('GEOGRAPHIC', 'Geographic'), ('CULTURAL', 'Cultural'), ('HISTORICAL', 'Historical'), ('CURRENT_EVENTS', 'Current Events'), ('ECONOMIC', 'Economic')], max_length=20)),
                ('text', models.TextField()),
                ('is_correct_path', models.BooleanField(default=False)),
                ('difficulty_level', models.PositiveIntegerField(default=1)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='games.case')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.country')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for Players'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused')], default='WAITING', max_length=20)),
                ('max_players', models.PositiveIntegerField(default=4)),
                ('budget', models.PositiveIntegerField(default=5000)),
                ('time_limit', models.PositiveIntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('cultural_significance', models.TextField(blank=True)),
                ('coordinates_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coordinates_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='places.city')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('ROOKIE', 'Rookie Detective'), ('DETECTIVE', 'Detective'), ('SENIOR', 'Senior Detective'), ('INSPECTOR', 'Inspector'), ('CHIEF', 'Chief Inspector')], default='ROOKIE', max_length=20)),
                ('budget_remaining', models.PositiveIntegerField(default=0)),
                ('cases_solved', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.country')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('FLIGHT_DIRECT', 'Direct Flight'), ('FLIGHT_CONNECTING', 'Connecting Flight'), ('TRAIN', 'Train'), ('SHIP', 'Ship'), ('CAR', 'Car')], max_length=20)),
                ('cost', models.PositiveIntegerField()),
                ('travel_time', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='places.country')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='games.player')),
                ('to_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='places.country')),
            ],
        ),
        migrations.CreateModel(
            name='GameCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('solved', models.BooleanField(default=False)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.case')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamesession')),
            ],
            options={
                'unique_together': {('session', 'case')},
            },
        ),
    ]
